<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Row caused error: {row}' => 'Строка, приведшая к ошибке: {row}',
    'Skip this column. Can be used multiple times' => 'Пропуск колонки. Можно использовать несколько раз',
    'All records' => 'Все записи',
    'Batch import' => 'Массовый импорт',
    'Excel/CSV file' => 'Excel или CSV файл',
    'Encoding' => 'Кодировка',
    'Fields' => 'Поля',
    'Separator' => 'Разделитель',
    'Skip first line' => 'Пропустить первую строку',
    'UTF-8' => '',
    'Upload and Import' => 'Загрузить и Импортировать',
    'Windows-1251' => '',
    'Import have been done successfully. Total imported records: {total}' => 'Импорт успешно завершен. Всего импортировано записей: {total}',
    'Available fields:' => 'Доступные поля: ',
    'Only suitable for CSV files, ignored for Excel files' => 'Используется только для файлов CSV, для файлов Excel - игнорируется'
];
